# Generated by Django 3.0.6 on 2021-10-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessages',
            new_name='ContactsMessages',
        ),
    ]
