# Generated by Django 3.0.6 on 2021-10-23 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('comp', models.CharField(default='none', max_length=200)),
                ('category', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.CharField(default='none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(default='none', max_length=200)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('name', models.CharField(default='none', max_length=200)),
                ('phone_number', models.DateTimeField(default=django.utils.timezone.now)),
                ('Address', models.CharField(default='none', max_length=200)),
                ('price', models.CharField(default='none', max_length=200)),
                ('status', models.CharField(default='pending', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='none', max_length=200)),
                ('password', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
